export const ALL_PERMISSIONS = [
  "VIEW_MEMBERS",
  "ADD_MEMBER",
  "EDIT_MEMBER",
  "DELETE_MEMBER",
  "VIEW_ATTENDANCE",
  "MANAGE_ATTENDANCE",
  "MANAGE_DIET_PLANS",
  "MANAGE_WORKOUT_PLANS",
  "MANAGE_TRAINERS",
  "ASSIGN_TRAINER",
  "ASSIGN_DIET_PLAN",
  "ASSIGN_WORKOUT_PLAN",
  "VIEW_ENQUIRIES",
  "MANAGE_COMPLAINTS",
  "VIEW_REPORTS",
  "MANAGE_MEMBERSHIPS",
] as const;

export type PermissionKey = (typeof ALL_PERMISSIONS)[number];
