import { prisma } from "@/lib/prisma";
import { requireOwner, apiError, apiResponse } from "@/lib/auth";
import { z } from "zod";

export const runtime = "nodejs";

const CreateIncentiveSchema = z.object({
  staffId: z.number(),
  incentiveType: z.string(),
  amount: z.number().min(1),
  reason: z.string(),
  clientId: z.number().optional().nullable(),
  membershipId: z.number().optional().nullable(),
  month: z.string(),
  year: z.number(),
  paymentStatus: z.enum(["Paid", "Pending"]).default("Pending"),
  notes: z.string().optional().nullable(),
});

const UpdateIncentiveStatusSchema = z.object({
  incentiveId: z.number(),
  paymentStatus: z.enum(["Paid", "Pending"]),
});

export async function GET() {
  try {
    await requireOwner();

    const incentives = await prisma.incentive.findMany({
      include: {
        staff: {
          select: {
            id: true,
            name: true,
            email: true,
            designation: true,
          }
        },
        client: {
          select: {
            id: true,
            name: true,
            email: true,
          }
        }
      },
      orderBy: { createdAt: "desc" }
    });

    // Calculate staff performance metrics
    const staffList = await prisma.staff.findMany({
      include: {
        trainerClients: {
          include: {
            client: {
              include: {
                memberships: true
              }
            }
          }
        },
        incentives: true
      }
    });

    const performanceMetrics = staffList.map(s => {
      const totalClientsHandled = s.trainerClients.length;
      const activeClients = s.trainerClients.filter(c => c.status === "Active").length;
      const totalIncentiveEarned = s.incentives.reduce((acc, i) => acc + i.amount, 0);
      const incentivePaid = s.incentives.filter(i => i.paymentStatus === "Paid").reduce((acc, i) => acc + i.amount, 0);
      const incentivePending = s.incentives.filter(i => i.paymentStatus === "Pending").reduce((acc, i) => acc + i.amount, 0);

      // Total revenue generated by clients assigned to this trainer
      let revenueGenerated = 0;
      s.trainerClients.forEach(tc => {
        tc.client.memberships.forEach(m => {
          revenueGenerated += m.amountPaid || 0;
        });
      });

      return {
        staffId: s.id,
        staffName: s.name,
        designation: s.designation,
        totalClientsHandled,
        activeClients,
        revenueGenerated,
        totalIncentiveEarned,
        incentivePaid,
        incentivePending,
      };
    });

    return apiResponse({
      incentives,
      performanceMetrics,
    });
  } catch (error) {
    console.error("[OWNER_INCENTIVES_GET]", error);
    return apiError("Internal server error", 500);
  }
}

export async function POST(req: Request) {
  try {
    const session = await requireOwner();
    const body = await req.json();
    const parse = CreateIncentiveSchema.safeParse(body);

    if (!parse.success) {
      return apiError("Invalid input: " + parse.error.issues.map(i => i.message).join(", "), 400);
    }

    const { staffId, incentiveType, amount, reason, clientId, membershipId, month, year, paymentStatus, notes } = parse.data;

    const incentive = await prisma.incentive.create({
      data: {
        staffId,
        incentiveType,
        amount,
        reason,
        clientId,
        membershipId,
        month,
        year,
        paymentStatus,
        paymentDate: paymentStatus === "Paid" ? new Date() : null,
        notes,
      },
      include: { staff: true }
    });

    // Audit log
    await prisma.auditLog.create({
      data: {
        action: "INCENTIVE_ADDED",
        performedByUserId: Number(session.sub),
        performedByName: session.name || session.email,
        role: "OWNER",
        targetRecordId: String(incentive.id),
        targetRecordType: "INCENTIVE",
        description: `Owner added incentive of ₹${amount} for ${incentive.staff.name} (${reason}).`,
      }
    }).catch(() => {});

    return apiResponse({ message: "Incentive record created.", incentive });
  } catch (error) {
    console.error("[OWNER_INCENTIVES_POST]", error);
    return apiError("Internal server error", 500);
  }
}

export async function PATCH(req: Request) {
  try {
    const session = await requireOwner();
    const body = await req.json();
    const parse = UpdateIncentiveStatusSchema.safeParse(body);

    if (!parse.success) return apiError("Invalid parameters", 400);

    const { incentiveId, paymentStatus } = parse.data;

    const incentive = await prisma.incentive.update({
      where: { id: incentiveId },
      data: {
        paymentStatus,
        paymentDate: paymentStatus === "Paid" ? new Date() : null,
      },
      include: { staff: true }
    });

    // Audit Log
    await prisma.auditLog.create({
      data: {
        action: "INCENTIVE_PAID",
        performedByUserId: Number(session.sub),
        performedByName: session.name || session.email,
        role: "OWNER",
        targetRecordId: String(incentiveId),
        targetRecordType: "INCENTIVE",
        description: `Owner marked incentive of ${incentive.staff.name} as ${paymentStatus}.`,
      }
    }).catch(() => {});

    return apiResponse({ message: `Incentive status updated to ${paymentStatus}.`, incentive });
  } catch (error) {
    console.error("[OWNER_INCENTIVES_PATCH]", error);
    return apiError("Internal server error", 500);
  }
}
